templates:
  - filename: "left_center_right"
    title: "Header with Main and sidebars on both sides"
    thumbnail: "/assets/templates/thumbnails/header_main_side.png"

  - filename: "main_and_three"
    title: "Large header with three equal content sections"
    thumbnail: "/assets/templates/thumbnails/header_main_side.png"
